advisTransaksi/urls.py
from django.urls import path
from . import views

app_name = 'advisTransaksi'

urlpatterns = [
    path('<id>/', views.hasil, name="hasil"),
]

tugaskelompok1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("utama.urls")),
    path('accounts/', include("allauth.urls")),
    path('login/', include("nofaldi_login.urls")),
    path('search/', include("nofaldi_kupon.urls")),
    path('kategori/', include("kategori_azhar.urls")),
    path('item/', include("wening_barang.urls")),
    path('transaksi/', include("advisTransaksi.urls")),
    path('ulasan/', include("ulasan.urls")),
    path('', include("keranjang.urls")),
]

ulasan/urls.py
# ulasan urls.py
from django.urls import path
from ulasan import views 

app_name = 'ulasan'

urlpatterns = [
    path('<str:nama_barang>/',  views.UlasanListView.as_view(), name='crud_ajax'),
    path('ajax/crud/create/',  views.CreateCrudUser.as_view(), name='crud_ajax_create'),
    path('ajax/crud/delete/',  views.DeleteCrudUser.as_view(), name='crud_ajax_delete'),
]

utama/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.homepage, name="homepage"),
]

wening_barang/urls.py
from django.urls import path
from . import views

app_name = 'wening_barang'

urlpatterns = [
    path('<str:nama_barang>/', views.barang_detail, name='barang_detail')
]

wening_barang/models.py
from django.db import models
from django.core.validators import MinValueValidator

# Create your models here.


class Barang(models.Model):
    CATEGORY_CHOICES = (
        ('Sneakers', 'Sneakers'),
        ('Boots', 'Boots'),
        ('Sandal', 'Sandal'),
        ('Slip On', 'Slip On'),
        ('Wedges', 'Wedges'),
        ('Flats', 'Flats'),
        ('Heels', 'Heels')
    )

    nama = models.CharField('Nama Barang', max_length=120, unique=True, null=False)
    harga = models.PositiveIntegerField(
        'Harga', validators=[MinValueValidator(1)], default=0)
    kategori = models.CharField(
        choices=CATEGORY_CHOICES, default='Sneakers', max_length=120)
    stok = models.PositiveIntegerField(
        'Stok', validators=[MinValueValidator(1)], default=0)
    deskripsi = models.TextField('Deskripsi Barang')

    def __str__(self):
        return self.nama

wening_barang/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .models import Barang

# Create your views here.

def barang_detail(request, nama_barang=''):
    barang = Barang.objects.get(nama=nama_barang)
    return render(request, 'barang_detail.html', {'barang': barang})

wening_barang/templates/barang_detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}{{ barang.nama }}{% endblock %}
{% block additional_css %}
<link rel="stylesheet" href="{% static 'stylebarang.css' %}" />{% endblock %}
{% block main_content %}

<div class="row text-muted mt-5">
    <div class="col-lg-6 text-center mb-5">
        <img src="{% static 'sepatu.png' %}" alt="">
        <p>{{ barang.kategori }}</p>
    </div>
    <div class="col-lg-6 mb-5">
        <h1 class="namabarang" id="{{barang.nama}}">{{ barang.nama }}</h1><br>
        <h4><b>Rp{{ barang.harga }}</b></h4>
        <p style="font-size: larger;">Stok yang tersedia: {{ barang.stok }}</p>
        <br>
        <p>Deskripsi barang:</p>
        <p>{{ barang.deskripsi }}</p>
        <div class="mt-5">
            {% if request.user.is_authenticated %}
            <!-- <a class="btn btn-modified" href="{% url 'advisTransaksi:hasil' barang.id %}" role="button">Buy</a> -->
            <button class="btn btn-modified" id="cart" role="button">Add to Cart <img
                    src="{% static 'cart-white.svg' %}"></button>
            <a class="btn btn-modified" href="{% url 'ulasan:crud_ajax' barang.nama %}" role="button">See Reviews</i></a>
            <a class="btn btn-modified" href="{% url 'advisTransaksi:hasil' barang.id %}" role="button">Buy</a>
            {% else %}
            <a class="btn btn-modified" href="{% url 'advisTransaksi:hasil' barang.id %}" role="button">Buy</a>
            {% endif %}

        </div>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="{% static 'addkeranjang.js' %}"></script>
{% endblock %}