nofaldi_login/urls.py
from django.urls import path
from . import views

app_name = "login"

urlpatterns = [
    path('', views.loginpage, name = "login-page"),
    path('register/', views.register, name="register"),
    path('logout/', views.logoutpage, name="logout-page")
]

tugaskelompok1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("utama.urls")),
    path('accounts/', include("allauth.urls")),
    path('login/', include("nofaldi_login.urls")),
    path('search/', include("nofaldi_kupon.urls")),
    path('kategori/', include("kategori_azhar.urls")),
    path('item/', include("wening_barang.urls")),
    path('transaksi/', include("advisTransaksi.urls")),
    path('ulasan/', include("ulasan.urls")),
    path('', include("keranjang.urls")),
]

utama/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.homepage, name="homepage"),
]

nofaldi_login/models.py
from django.db import models

# Create your models here.

nofaldi_login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User

def loginpage(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('/')

    return render(request,'login.html')

def register(request):
    if request.method == "POST":
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        first_name = request.POST['firstname']
        last_name = request.POST['lastname']

        user = User.objects.create_user(username, email, password)
        user.first_name = first_name
        user.last_name = last_name
        user.save()
        return redirect('/login/')

    return render(request,'register.html')

def logoutpage(request):
    if request.user.is_authenticated:
        logout(request)
        return redirect('/')
    

nofaldi_login/templates/login.html
<!DOCTYPE html>
{% load static %}
{% load socialaccount %}
{% providers_media_js %}
<html>

<head>
    <title>Login To Your Account</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Poppins:600&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/a81368914c.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
    <img class="wave" src="{% static 'img/wave.svg' %}">
    <div class="container">
        <div class="img">
            <img src="{% static 'img/celeb.svg' %}">
        </div>
        <div class="login-content">
            <form action="" method="POST" class="posted">
                {% csrf_token %}
                <img src="{% static 'img/avatar.svg' %}">
                <h2 class="title">Log In</h2>
                <div class="input-div one">
                    <div class="i">
                        <i class="fas fa-user"></i>
                    </div>
                    <div class="div">
                        <input type="text" name="username" class="input" placeholder="Username" required>
                    </div>
                </div>
                <div class="input-div pass">
                    <div class="i">
                        <i class="fas fa-envelope"></i>
                    </div>
                    <div class="div">
                        <input type="password" name="password" class="input" placeholder="Password" required>
                    </div>
                </div>
                {{ form.errors }}
                <a href="{% provider_login_url 'google' %}"><i class="fab fa-google"></i></a>
                <a href="{% url 'login:register' %}" id="signup">Sign Up Now</a>
                <input type="submit" class="btn" value="Log In" name="login">
            </form>
        </div>
    </div>
</body>

</html>

nofaldi_login/templates/register.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <title>Register Your Account</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Poppins:600&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/a81368914c.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
    <img class="wave" src="{% static 'img/wave.svg' %}">
    <div class="container">
        <div class="img">
            <img src="{% static 'img/bg.svg' %}">
        </div>
        <div class="login-content">
            <form action="" method="POST" class="posted">
                {% csrf_token %}
                <img src="{% static 'img/avatar.svg' %}">
                <h2 class="title">Register</h2>
                <div class="input-div one">
                    <div class="i">
                        <i class="fas fa-user"></i>
                    </div>
                    <div class="div">
                        <input type="text" name="username" class="input" placeholder="username" required>
                    </div>
                </div>
                <div class="input-div one">
                    <div class="i">
                        <i class="fas fa-users"></i>
                    </div>
                    <div class="div">
                        <input type="text" name="firstname" class="input" placeholder="First Name" required>
                    </div>
                </div>
                <div class="input-div one">
                    <div class="i">
                        <i class="fas fa-users"></i>
                    </div>
                    <div class="div">
                        <input type="text" name="lastname" class="input" placeholder="Last Name" required>
                    </div>
                </div>
                <div class="input-div pass">
                    <div class="i">
                        <i class="fas fa-envelope"></i>
                    </div>
                    <div class="div">
                        <input type="email" name="email" id="email" class="input" placeholder="email" required>
                    </div>
                </div>
                <div class="input-div pass">
                    <div class="i">
                        <i class="fas fa-lock"></i>
                    </div>
                    <div class="div">
                        <input type="password" name="password" id="password" class="input" placeholder="password" required>
                    </div>
                </div>
                {{ form.errors }}
                <a href="{% url 'login:login-page' %}" id="signin">Already have an account?</a>
                <input type="submit" class="btn" value="Sign Up" name="signup">
            </form>
        </div>
    </div>
</body>

</html>