keranjang/urls.py
from django.urls import path
from . import views


app_name = 'keranjang'

urlpatterns = [
    path('cart/', views.keranjang, name='keranjang'),
    path('add/', views.add_to_keranjang, name='add-to-keranjang'),
    path('reduce/', views.reduce_quantity, name='reduce-quantity'),
    path('remove/', views.remove_from_keranjang,
         name='remove-from-keranjang'),
    # path('usekupon/', views.usekupon, name='use-kupon'),
    # path('carinamakupon/', views.carinamakupon, name='carinamakupon'),
    # path('caripersenkupon/', views.caripersenkupon, name='caripersenkupon'),
    path('beli/', views.beli, name='beli'),
]

nofaldi_login/urls.py
from django.urls import path
from . import views

app_name = "login"

urlpatterns = [
    path('', views.loginpage, name = "login-page"),
    path('register/', views.register, name="register"),
    path('logout/', views.logoutpage, name="logout-page")
]

tugaskelompok1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("utama.urls")),
    path('accounts/', include("allauth.urls")),
    path('login/', include("nofaldi_login.urls")),
    path('search/', include("nofaldi_kupon.urls")),
    path('kategori/', include("kategori_azhar.urls")),
    path('item/', include("wening_barang.urls")),
    path('transaksi/', include("advisTransaksi.urls")),
    path('ulasan/', include("ulasan.urls")),
    path('', include("keranjang.urls")),
]

utama/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.homepage, name="homepage"),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width={device-width}, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- <link rel="stylesheet" href="{% static 'stylenavbar.css' %}"> -->
    <title>{% block title %}TWAAN{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'TK1_Bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'stylemaincontent.css' %}">
    {% block additional_css %}{% endblock %}
</head>

<body>
    {% include 'navbar.html' %}
    <div class="main-content">
        {% block main_content %}
        {% endblock %}
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
</body>
<footer>
    {% include 'footer.html' %}
</footer>

</html>

templates/footer.html
{% load static %}
<footer class="footer">
    <div class="container">
        <hr>
        <div class="row pl-4">
            <div class="col-lg-5 col-md-5 col-sm-12 mb-4 text-muted">
                <div class="row ml-1">
                    <h4>follow us on</h4>
                </div>
                <div class="row ml-1">
                    <img class="mr-3" width="30px" height="30px" src="{% static 'ig.png' %}" alt="" srcset="">
                    <img class="mr-3" width="30px" height="30px" src="{% static 'twitter.png' %}" alt="" srcset="">
                    <img class="mr-3" width="30px" height="30px" src="{% static 'fb.png' %}" alt="" srcset="">
                </div>
            </div>
            <div class="col-lg-7 col-md-7 col-sm-12 text-muted">
                <h4>more about us</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
                    ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
                    laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in
                    voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat.</p>
            </div>
        </div>

    </div>
</footer>

templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light ">
    <a class="navbar-brand" href="/"><b><i>TWAAN</i></b></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" aria-expanded="false"
        aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item ml-5 mr-3"><a href="/" class="nav-link">home</a></li>
            <li class="nav-item ml-3 mr-3"><a href="/kategori" class="nav-link">category</a>
                {% if request.user.is_authenticated %}
            <li class="nav-item ml-3 mr-3"><a id="auth" class="nav-link" href="{% url 'login:logout-page' %}">logout
                    <span style="font-size: 0.75rem;">({{request.user}})</span></a></li>
            {% else %}
            <li class="nav-item ml-3 mr-3"><a id="auth" class="nav-link" href="{% url 'login:login-page' %}">login</a>
            </li>
            {% endif %}
            </li>
        </ul>
        {% if request.user.is_authenticated %}
        <a href="{% url 'keranjang:keranjang'%}">
            <img src="{% static 'cart.svg' %}" height="45x" style="margin-right: 1rem;">
        </a>
        {% endif %}
        <form class="form-inline my-2 my-lg-0" action="/search/" method="POST">
            {% csrf_token %}
            <input class="form-control mr-sm-2" id="searchbar" type="search" name="srh"
                placeholder="search a coupon...">
            <input type="submit" value="search" class="btn btn-outline-modified my-2 my-sm-0">
        </form>
    </div>
</nav>