home_page/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.hasil,name="hasil-kupon"),
]

tugaskelompok1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("utama.urls")),
    path('accounts/', include("allauth.urls")),
    path('login/', include("nofaldi_login.urls")),
    path('search/', include("nofaldi_kupon.urls")),
    path('kategori/', include("kategori_azhar.urls")),
    path('item/', include("wening_barang.urls")),
    path('transaksi/', include("advisTransaksi.urls")),
    path('ulasan/', include("ulasan.urls")),
    path('', include("keranjang.urls")),
]

utama/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.homepage, name="homepage"),
]

wening_barang/urls.py
from django.urls import path
from . import views

app_name = 'wening_barang'

urlpatterns = [
    path('<str:nama_barang>/', views.barang_detail, name='barang_detail')
]

home_page/models.py
from django.db import models

# Create your models here.

utama/models.py
from django.db import models

# Create your models here.

home_page/views.py
from django.shortcuts import render

# Create your views here.

utama/views.py
from django.shortcuts import render
from wening_barang.models import Barang
# Create your views here.


def homepage(request):
    barang = Barang.objects.all()
    map = {
        'barang' : barang,
    }
    return render(request, 'homepage.html',map)

utama/templates/homepage.html
{% extends "base.html" %}
{% load static %}

{% block main_content %}
<div class="row justify-content-center">
    <div class="col-lg-4 col-sm-12">
        <img class=" mb-5" src="{% static 'sepatu.jpg' %}" style="height: 200px; width: 300px;" alt="Sepatu">
        <img class="" src="{% static 'sepatulagi.png' %}" style="height: 200px; width: 300px;" alt="Sepatu">
    </div>
    <div class="col-lg-4 col-sm-12 mt-lg-0  mt-5" style="max-height: 60vh; overflow: auto;">
        <table class="table table-barang mb-5" style="text-align: center;">
            {% for x in barang %}
            <tr>
                <td>
                    <a href="{% url 'wening_barang:barang_detail' x.nama %}">{{x.nama}}</a>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
    <div class="col-lg-4 col-sm-12">
        <img src="{% static 'iklan.png' %}" style="height: 450px; width: 300px;" alt="Iklan">
    </div>
</div>
{% endblock %}